language: node_js
cache:
  yarn: true
  npm: true
node_js:
  - '14'
script:
  - cd hello && npm i && CI=true npm test
  - cd hello-functional && npm i && CI=true npm test
  - cd randompeople && npm i && CI=true npm test